name = "driver-scheduling-api"
main = "deployment/cloudflare/main.py"
compatibility_date = "2024-08-01"

# Custom domain configuration
# Add your domain in Cloudflare Dashboard under Workers & Pages > Custom domains
# Example: api.yourdomain.com

[env.production]
name = "driver-scheduling-api-prod"
# Custom domain for production: api.yourdomain.com

[env.staging]
name = "driver-scheduling-api-staging"
# Custom domain for staging: staging-api.yourdomain.com

# Environment variables will be set via Cloudflare Dashboard or CLI
# Use: wrangler secret put <SECRET_NAME>

# Required secrets (set these in Cloudflare Dashboard):
# - DATABASE_URL
# - SUPABASE_PASSWORD  
# - SUPABASE_URL
# - SUPABASE_KEY
# - GCF_URL
# - DEBUG
# - LOG_LEVEL

[build]
command = "pip install -r requirements.txt"

[vars]
PORT = "8000"
WEEK_DAYS = "7"
DEBUG = "false"
LOG_LEVEL = "INFO"